spring:
  datasource:
    url: jdbc:mysql://116.63.170.14:3307/bm?useSSL=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&characterEncoding=utf8

    username: root
    password: toor
    driver-class-name: com.mysql.cj.jdbc.Driver
    spring:
      thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML5
        encoding: UTF-8
        content-type: text/html
        cache: false
    hikari:
      max-lifetime: 500000
  jpa:
    hibernate:
#     更新或者创建数据表结构
      ddl-auto: update
#    控制台显示SQL
    show-sql: true
